CUDA_VISIBLE_DEVICES=0 python -m flashrag.retriever.index_builder \
    --retrieval_method e5 \
    --model_path intfloat/e5-base-v2 \
    --corpus_path /projects/nucar/feric.z/FLashRAG-z/test_sample_2018_sent.jsonl \
    --save_dir /projects/nucar/feric.z/wikiindex2 \
    --use_fp16 \
    --max_length 256 \
    --batch_size 512 \
    --pooling_method mean \
    --faiss_type Flat \
    --save_embedding